package FomInteractions.Events;

public enum EventType {
    SEAT_TAKEN,
    SEAT_FREED,
    CLIENT_ARRIVED,
    CLIENT_LEFT_QUEUE,
    CLIENT_WAITING,
    CLIENT_SERVICED,
    CLIENT_FINISHED_MEAL,
    ORDER_PLACED,
    ORDER_FILLED,
    OBJECT_UPDATE,
    OBJECT_REGISTERED,
    OBJECT_DELETED,
    FINISH
}
